apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-cuda
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-test
    image: nvcr.io/nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args:
    - |
      echo "=== Checking GPU devices ==="
      ls -la /dev/nvidia* 2>&1 | head -10
      echo ""
      echo "=== Checking NVIDIA libraries ==="
      ldconfig -p | grep nvidia | head -10
      echo ""
      echo "=== Checking LD_LIBRARY_PATH ==="
      echo $LD_LIBRARY_PATH
      echo ""
      echo "=== Finding CUDA libraries ==="
      find /usr -name "libcuda.so*" 2>/dev/null | head -5
      echo ""
      echo "=== Trying nvidia-smi ==="
      nvidia-smi || echo "nvidia-smi failed"
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: true
